


class FN:

    FLD_ACCESSTOKEN = "accessToken"
    FLD_ADDRESS = "address"
    FLD_BACKUP = "backup"
    FLD_CAMERACOUNT = "cameraCount"
    FLD_CANSTREAM = "canStream"
    FLD_CANTIMELAPSE = "canTimelapse"
    FLD_CLIENTID ="clientId"
    FLD_CMD = "command"
    FLD_DATA = "data"
    FLD_DICTIONARY = "dictionary"
    FLD_DISABLENOTIFY = "disableNotify"
    FLD_FS20COUNT = "fs20Count"
    FLD_FS20SENSORCOUNT = "fs20SensorCount"
    FLD_HMS100TCOUNT = "hms100tCount"
    FLD_HMS100TFCOUNT = "hms100tfCount"
    FLD_HOST = "host"
    FLD_ID = "id"
    FLD_INVERSE = "inverse"
    FLD_KSH300COUNT = "ksh300Count"
    FLD_LASTUPDATETIME = "lastUpdateTime"
    FLD_LASTUPDATETYPE = "lastUpdateType"
    FLD_LOCALE = "locale"
    FLD_LOCALID = "localId"
    FLD_MAX = "max"
    FLD_MESSAGE = "message"
    FLD_MIN = "min"
    FLD_MSGTYPE = "msgType"
    FLD_NAME = "name"
    FLD_NETIOCOUNT = "netioCount"
    FLD_PEERCOUNT = "peerCount"
    FLD_PID = "pid"
    FLD_PUBLIC_KEY = "publicKey"
    FLD_RPICAMCOUNT = "rpicamCount"
    FLD_SENDER_ID = "senderId"
    FLD_SERVERID = "serverId"
    FLD_STATUS = "status"
    FLD_SWITCHCOUNT = "switchCount"
    FLD_TEMPERATURECOUNT = "temperatureCount"
    FLD_TIMELAPSEMP4 = "timelapseMP4"
    FLD_TIMELAPSECODEC = "timelapseCodec"
    FLD_TIMESTAMP = "timeStamp"
    FLD_TOKEN = "token"
    FLD_ULTRASONICCOUNT = "ultrasonicCount"
    FLD_UPTIME = "uptime"
    FLD_USER = "user"
    FLD_VALUE = "value"
    CMD_ABOUT = "about"
    CMD_CONFIG = "config"
    CMD_SWITCH = "switch"
    CMD_STATUS = "status"
    CMD_ULTRASONIC = "ultrasonic"
    CMD_TEMPERATURE = "temperature"
    CMD_HISTORY24 = "history24"
    CMD_HISTORY365 = "history365"
    CMD_TOKEN = "fcmToken"
    CMD_REFRESH = "refresh"
    CMD_SHINE = "shine"
    CMD_CANBACKUP = "canBackup"
    CMD_BACKUP = "backup"
    CMD_SNAPSHOT = "snapshot"
    FLAG_ROAMING = "roaming"

    ok = "ok"
    fail = "fail"

    ON = "on"
    OFF = "off"